### ISSUE TITLE
mpd has to be restarted following suspension

### ISSUE THREAD

**Issue by samhh** [samhh/dotfiles#209]
Started happening around the time of the switch to Pipewire.

**Comment by samhh** [comment]
If this is ever actioned it would probably solve this: https://github.com/MusicPlayerDaemon/MPD/issues/1012

**Comment by samhh** [comment]
mpd-mpris logs look fine. Playback controls appear to work fine via both keyboard (playerctl) and mpc. Notably the playback state seems to reset a bit upon pausing.

**Comment by ploz** [comment]
Having a similar issue. I am running Pipewire w/ mpd's audio_output type set to "pulse". Unplugging my DAC causes mpd to stall until restarted. I've enabled verbose logging, and it did not output anything out of the ordinary upon stalling.

While running mpd with the audio_output type set to "alsa", it does not need to be restarted in order to resume playback (although it does have to be paused → unpaused).

**Comment by yorokobi** [comment]
Possibly related: https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1354

**Comment by zarkone** [comment]
have similar observations, after switching to pipewire I got mpd stuck on switching to the next track

**Comment by samhh** [comment]
N.B. pipewire support is now implemented in mpd but I think it's not released yet as of 0.22.x.

**Comment by zarkone** [comment]
created an issue with a workaround :point_up:  -- specifying audio_output "pulse" explicitly fixed this for me

**Comment by samhh** [comment]
Seems to have resolved itself with a recent update.
